MAP = 'cutman.tmx'
SCALE2X = False

MAP_DEBUG = False
PLAYER_DEBUG = False
PLAYER_INVINCIBLE = True
DEBUG_START_ZONE = None
DEBUG_START_POSITION = None
DEBUG_START_ZONE = 'z11'
DEBUG_START_POSITION = 1825, 721