MAP = 'cutman.tmx'
SCALE2X = False

MAP_DEBUG = False
PLAYER_DEBUG = False
PLAYER_INVINCIBLE = False
DEBUG_START_ZONE = None
DEBUG_START_POSITION = None
# DEBUG_START_ZONE = 'z12'
# DEBUG_START_POSITION = 2129, 948